### ISSUE TITLE
Appveyor support?

### ISSUE THREAD

**Issue by amilajack** [uber/image-diff#43]
Wondering if this project will get windows support, ensured by appveyor.

**Comment by dawsonbotsford** [comment]
Since we don't have Windows machines, it's not likely that Windows will be tested on. It might be worth it ensure the current functions are Windows safe and then do appveyor testing anyways. What are your thougths @mlmorg?

@amilajack, does it already work for you on Windows? If so, what versions of things are you running? Consider using [`sist shell node`](https://github.com/dawsonbotsford/sist) to quickly achieve that info.

**Comment by amilajack** [comment]
I actually dont use windows directly. But my app uses image-diff to test differences. It would be nice if the same tests could run on windows.

**Comment by twolfson** [comment]
AppVeyor support sounds reasonable but it can be time consuming to set up (i.e. push, wait for AppVeyor to fail for a trivial mistake, rinse, and repeat). I would be up for setting it up but I would need repo access again =/

That being said @amilajack, you didn't answer the question about if `image-diff` fails/throws an error on Windows right now =/

**Comment by amilajack** [comment]
I can't test on windows because I dont have a windows machine.

**Comment by twolfson** [comment]
Sooo we could be fine on Windows then? This is more about getting 1 more system that we automatically check via CI?

**Comment by dawsonbotsford** [comment]
Since y'all aren't in immediate need of Windows support, and it's not the standard to run Windows CI on Uber Open-Source repo's, I'm closing this. Feel free to re-open if the need for Windows support/testing becomes more important.

**Comment by twolfson** [comment]
Fwiw, Microsoft offers Windows VMs for testing Internet Explorer which can be reused for testing on Windows:

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
